hyperparameters:
  image_size: None

inference:
  sam3_text_prompt: "A window"
  sam3_score_threshold: 0.8
  sam_consecutive_iterations: 10
  num_points: 1000
  extend_ratio: 0.2
  min_instance_area_ratio: 0.001  # discard instances smaller than 0.1% of image area
